In [16]:
# dataFrame
#collection of series is called dataFrame

import numpy as np
import pandas as pd

In [17]:
data = {
  "name":["kaif","sadhik","ishu","sonu"],
  "gender":["m","m","f","m"],
  "age":[22,14,11,19],
  "study":["grad","school","school","college"] 
}

In [18]:
df = pd.DataFrame(data)

In [19]:
data2 = [
  ["kaif",22,"grad"],
  ["riyaz",19,"college"],
  ["munna",16,"diploma"]
]

In [20]:
pd.DataFrame(data2)

       0   1        2
0   kaif  22     grad
1  riyaz  19  college
2  munna  16  diploma

In [21]:
col = ["name","age","work"]

In [22]:
pd.DataFrame(data2,columns=col)

    name  age     work
0   kaif   22     grad
1  riyaz   19  college
2  munna   16  diploma

In [24]:
#adding col

df["place"] = ["hyd","wgl","wgl","pkpl"]

In [25]:
df

     name gender  age    study place
0    kaif      m   22     grad   hyd
1  sadhik      m   14   school   wgl
2    ishu      f   11   school   wgl
3    sonu      m   19  college  pkpl

In [27]:
df.drop(["study"],axis = 1)

     name gender  age place
0    kaif      m   22   hyd
1  sadhik      m   14   wgl
2    ishu      f   11   wgl
3    sonu      m   19  pkpl

In [28]:
df.drop(2,axis = 0)

     name gender  age    study place
0    kaif      m   22     grad   hyd
1  sadhik      m   14   school   wgl
3    sonu      m   19  college  pkpl

In [29]:
df

     name gender  age    study place
0    kaif      m   22     grad   hyd
1  sadhik      m   14   school   wgl
2    ishu      f   11   school   wgl
3    sonu      m   19  college  pkpl

In [30]:
df.drop("study",axis=1,inplace=True)

In [31]:
df

     name gender  age place
0    kaif      m   22   hyd
1  sadhik      m   14   wgl
2    ishu      f   11   wgl
3    sonu      m   19  pkpl

In [32]:
df["name"]

0      kaif
1    sadhik
2      ishu
3      sonu
Name: name, dtype: str

In [33]:
df[["name","age"]]

     name  age
0    kaif   22
1  sadhik   14
2    ishu   11
3    sonu   19

In [43]:
df.loc[[1,3]]

     name gender  age place
1  sadhik      m   14   wgl
3    sonu      m   19  pkpl

In [44]:
df

     name gender  age place
0    kaif      m   22   hyd
1  sadhik      m   14   wgl
2    ishu      f   11   wgl
3    sonu      m   19  pkpl

In [46]:
df.loc[[2,3]][["name","gender"]]

   name gender
2  ishu      f
3  sonu      m

In [49]:
#conditions

df[df["age"]<=20]

     name gender  age place
1  sadhik      m   14   wgl
2    ishu      f   11   wgl
3    sonu      m   19  pkpl

In [56]:
df[(df["age"]<=20) & (df["gender"]=="m")]

     name gender  age place
1  sadhik      m   14   wgl
3    sonu      m   19  pkpl