In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "category": [
        "Electronics", "Clothing", "Grocery", "Electronics", "Clothing",
        "Grocery", "Electronics", "Clothing", "Grocery", "Electronics",
        "Clothing", "Grocery"
    ],
    "store": [
        "Store A", "Store B", "Store A", "Store C", "Store B",
        "Store C", "Store A", "Store C", "Store B", "Store C",
        "Store A", "Store B"
    ],
    "sales": [
        1200, 850, 450, 2100, 950,
        600, 1500, 1100, 520, 1800,
        700, 750
    ],
    "quantity": [
        5, 12, 20, 7, 15,
        25, 6, 18, 22, 8,
        10, 30
    ],
    "date": [
        "2026-01-05", "2026-01-06", "2026-01-07", "2026-01-08",
        "2026-01-10", "2026-01-12", "2026-01-15", "2026-01-18",
        "2026-01-20", "2026-01-22", "2026-01-25", "2026-01-28"
    ]
}

In [5]:
df = pd.DataFrame(data)

In [6]:
df

       category    store  sales  quantity        date
0   Electronics  Store A   1200         5  2026-01-05
1      Clothing  Store B    850        12  2026-01-06
2       Grocery  Store A    450        20  2026-01-07
3   Electronics  Store C   2100         7  2026-01-08
4      Clothing  Store B    950        15  2026-01-10
5       Grocery  Store C    600        25  2026-01-12
6   Electronics  Store A   1500         6  2026-01-15
7      Clothing  Store C   1100        18  2026-01-18
8       Grocery  Store B    520        22  2026-01-20
9   Electronics  Store C   1800         8  2026-01-22
10     Clothing  Store A    700        10  2026-01-25
11      Grocery  Store B    750        30  2026-01-28

In [27]:
## group by category and calculate sum of sales

g_c = df.groupby("category")

In [28]:
g_c['sales'].sum()

category
Clothing       3600
Electronics    6600
Grocery        2320
Name: sales, dtype: int64

In [31]:
g_s = df.groupby("store")["sales"].sum()
g_s

store
Store A    3850
Store B    3070
Store C    5600
Name: sales, dtype: int64

In [49]:
## group by multiple cols

df.groupby(["store","category"])["sales"].sum()

store    category
Store A  Clothing        700
         Electronics    2700
         Grocery         450
Store B  Clothing       1800
         Grocery        1270
Store C  Clothing       1100
         Electronics    3900
         Grocery         600
Name: sales, dtype: int64

In [51]:
df

       category    store  sales  quantity        date
0   Electronics  Store A   1200         5  2026-01-05
1      Clothing  Store B    850        12  2026-01-06
2       Grocery  Store A    450        20  2026-01-07
3   Electronics  Store C   2100         7  2026-01-08
4      Clothing  Store B    950        15  2026-01-10
5       Grocery  Store C    600        25  2026-01-12
6   Electronics  Store A   1500         6  2026-01-15
7      Clothing  Store C   1100        18  2026-01-18
8       Grocery  Store B    520        22  2026-01-20
9   Electronics  Store C   1800         8  2026-01-22
10     Clothing  Store A    700        10  2026-01-25
11      Grocery  Store B    750        30  2026-01-28

In [52]:
df["sales"].agg(["mean","median","min","max","count"]).round()

mean      1043.0
median     900.0
min        450.0
max       2100.0
count       12.0
Name: sales, dtype: float64