# merging - joining - concatination

In [1]:
import numpy as np
import pandas as pd

In [2]:
employees = pd.DataFrame({
  "emp_id":[1,2,3,4,5],
  "emp_name":["kaif","ayaan","gautham","tejaswi","pranay"],
  "dept":["IT","architecture","business","designing","HR"]
})

salaries = pd.DataFrame({
  "emp_id":[1,2,3,8,10],
  "salary":[45000,120000,70000,37000,60000],
  "bonus" : [10000,2000,3000,4500,7000] 
})

In [3]:
employees

   emp_id emp_name          dept
0       1     kaif            IT
1       2    ayaan  architecture
2       3  gautham      business
3       4  tejaswi     designing
4       5   pranay            HR

In [4]:
df = pd.merge(employees,salaries,how="inner")
df

   emp_id emp_name          dept  salary  bonus
0       1     kaif            IT   45000  10000
1       2    ayaan  architecture  120000   2000
2       3  gautham      business   70000   3000

In [5]:
df = pd.merge(employees,salaries,how="right")
df

   emp_id emp_name          dept  salary  bonus
0       1     kaif            IT   45000  10000
1       2    ayaan  architecture  120000   2000
2       3  gautham      business   70000   3000
3       8      NaN           NaN   37000   4500
4      10      NaN           NaN   60000   7000

In [6]:
df1 = pd.DataFrame({
  "A":["A0","A1","A2"],
  "B":["B0","B1","B2"],
  "C":["C0","C1","C2"]
})

df2 = pd.DataFrame({
  "A":["A3","A4","A5"],
  "B":["B3","B4","B5"],
  "C":["C3","C4","C5"]
})

In [7]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [8]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [9]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [10]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [11]:
# joining 2 data frames #

In [12]:
name = pd.DataFrame({
  "name":["kaif","gautham","sathish"]
},index=[1,2,3])

age = pd.DataFrame({
  "age":[23,22,22]
},index=[2,3,4])

In [13]:
name

      name
1     kaif
2  gautham
3  sathish

In [14]:
age

   age
2   23
3   22
4   22

In [15]:
age.join(name,how='outer')

    age     name
1   NaN     kaif
2  23.0  gautham
3  22.0  sathish
4  22.0      NaN