In [1]:
# missing data

import numpy as np
import pandas as pd

In [2]:
data = {
  "name":["kaif","aaryan","roxoy",pd.NA],
  "age":[pd.NA,27,25,18],
  "occupation":["data eng",pd.NA,pd.NA,pd.NA]
}

In [3]:
data

{'name': ['kaif', 'aaryan', 'roxoy', <NA>],
 'age': [<NA>, 27, 25, 18],
 'occupation': ['data eng', <NA>, <NA>, <NA>]}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

     name   age occupation
0    kaif  <NA>   data eng
1  aaryan    27        NaN
2   roxoy    25        NaN
3     NaN    18        NaN

In [6]:
df.isna()

    name    age  occupation
0  False   True       False
1  False  False        True
2  False  False        True
3   True  False        True

In [7]:
df.isna().sum()

name          1
age           1
occupation    3
dtype: int64

In [8]:
df.isnull()

    name    age  occupation
0  False   True       False
1  False  False        True
2  False  False        True
3   True  False        True

In [9]:
df[df.isna().any(axis = 1)]

     name   age occupation
0    kaif  <NA>   data eng
1  aaryan    27        NaN
2   roxoy    25        NaN
3     NaN    18        NaN

In [10]:
df.dropna()

Empty DataFrame
Columns: [name, age, occupation]
Index: []

In [11]:
df

     name   age occupation
0    kaif  <NA>   data eng
1  aaryan    27        NaN
2   roxoy    25        NaN
3     NaN    18        NaN

In [12]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [13]:
df

     name   age occupation
0    kaif  <NA>   data eng
1  aaryan    27        NaN
2   roxoy    25        NaN
3     NaN    18        NaN

In [14]:
df["name"].fillna("aaradya")

0       kaif
1     aaryan
2      roxoy
3    aaradya
Name: name, dtype: str

In [15]:
df

     name   age occupation
0    kaif  <NA>   data eng
1  aaryan    27        NaN
2   roxoy    25        NaN
3     NaN    18        NaN

In [16]:
# df.fillna(0)

In [17]:
# df.fillna({
#   "name":"unknown",
#   "age":"20",
#   "occupation":"unemployed"
# })

In [18]:
# df["age"].fillna(df["age"].median())

In [19]:
df

     name   age occupation
0    kaif  <NA>   data eng
1  aaryan    27        NaN
2   roxoy    25        NaN
3     NaN    18        NaN

In [20]:
df

     name   age occupation
0    kaif  <NA>   data eng
1  aaryan    27        NaN
2   roxoy    25        NaN
3     NaN    18        NaN

In [21]:
df["age"] = df["age"].bfill()
df

     name age occupation
0    kaif  27   data eng
1  aaryan  27        NaN
2   roxoy  25        NaN
3     NaN  18        NaN

In [22]:
df["occupation"] = df["occupation"].ffill()
df

     name age occupation
0    kaif  27   data eng
1  aaryan  27   data eng
2   roxoy  25   data eng
3     NaN  18   data eng